name: '${name}'
version: '${project.version}'
description: '${project.description}'

main: groundbreaking.newbieguard.NewbieGuard
api-version: 1.16

author: Groundbreaking
website: '${url}'

softdepend: [ LuckPerms, PlaceholderAPI ]

commands:
  newbieguard:
    aliases:
      - ng

permissions:
  newbieguard.reload:
    default: op

  newbieguard.help:
    default: op

  newbieguard.bypass.messages:
    default: op

  newbieguard.bypass.coloncommands:
    default: op